title: "Vasyl Pryimak — Blog"
description: "Software Engineering, embedded systems та все що між ними."
author: "Vasyl Pryimak"
url: "https://vasyl-pryimak.github.io"

remote_theme: jekyll/minima

minima:
  skin: auto

show_excerpts: true

header_pages:
  - blog.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /posts/:title/
